### ISSUE TITLE
Feature request - Add support for the session_token option

### ISSUE THREAD

**Issue by BenKanouse** [jrochkind/faster_s3_url#13]
If a user is authenticating to S3 using a temporary security token that was obtained through a call to AWS Security Token Service, the `S3::Client` allows a user to set the session_token option.  In AWS this option ends up setting the `X-Amz-Security-Token` param in the url.

I would like to be able to pass in a `session_token` to the `Builder` class and have this resulting url match AWS's url when a `session_token` is passed in.

Docs on `Aws::S3::Client` which talk about the session_token option:
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html

Docs on how that token is used to add the `X-Amz-Security-Token` param:
https://docs.aws.amazon.com/STS/latest/APIReference/CommonParameters.html`

**Comment by BenKanouse** [comment]
I made a Pull Request for this feature here: https://github.com/jrochkind/faster_s3_url/pull/12

**Comment by jrochkind** [comment]
Closed in #12
